/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/overview', 'getting-started/linux',
              'getting-started/macos', 'getting-started/windows',
              'getting-started/tutorial', 'getting-started/advanced',
              'getting-started/cluster'],
    },
    {
      type: 'category',
      label: 'Documentation',
      items: ['documentation/overview', 'documentation/polytope',
              'documentation/polytopeface', 'documentation/triangulation',
              'documentation/toricvariety', 'documentation/calabiyau',
              'documentation/cone', 'documentation/other',
              'documentation/config', 'documentation/experimental',
              'documentation/license'],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
