#!/bin/bash

# Function that prints help
showHelp() {
cat << EOF
CYTools: A software package for analyzing Calabi-Yau hypersurfaces in toric varieties.

Usage: cytools [OPTIONS]
The CYTools Docker image must be built for this script to work

Options:
 -h          Display help

 -b          Start a bash terminal in the CYTools container instead of Jupyter Lab.

 -d          Specify the directory to mount on the container. Default is ~ .

 --update    Update CYTools

For more detailed instructions please visit https://cytools.liammcallistergroup.com

EOF
}

# Function that updates cytools
updateCYTools() {
  cd /tmp/
  tmp_dir="cytools-update-$RANDOM"
  mkdir $tmp_dir
  cd $tmp_dir
  curl -s https://api.github.com/repos/LiamMcAllisterGroup/cytools/tags | grep "tarball_url" | grep -Eo 'https://[^\"]*' | sed -n '1p' | xargs curl -s -L -o - | tar -xz --strip-components 1
  make install
  cd /tmp/
  rm -rf $tmp_dir
}

# Function that (partially) updates cytools quickly
updateCYToolsFast() {
  cd /tmp/
  tmp_dir="cytools-update-$RANDOM"
  mkdir $tmp_dir
  cd $tmp_dir
  curl -s https://api.github.com/repos/LiamMcAllisterGroup/cytools/tags | grep "tarball_url" | grep -Eo 'https://[^\"]*' | sed -n '1p' | xargs curl -s -L -o - | tar -xz --strip-components 1
  make build-fast
  cd /tmp/
  rm -rf $tmp_dir
}

# Make sure that the script is not being run as root
userid=$(id -u)
if [[ "$userid" == "0" ]]
then
  echo "Please run the script as a non-root user."
  exit
fi
port=$(( $userid + 2875 ))

# We first parse the input parameters and set the way the container will run
runbash=false
mountdir=~
while getopts "hbd:-:" OPT
do
  case $OPT in
    h)
      showHelp
      exit 0
      ;;
    b)
      runbash=true
      ;;
    d)
      mountdir=$OPTARG
      if [ -z "$mountdir" ]
      then
        echo "A directory must be specified after -d flag."
        exit
      fi
      ;;
    -)
      case "${OPTARG}" in
        update)
          updateCYTools
          exit 0
          ;;
        update-fast)
          updateCYToolsFast
          exit 0
          ;;
        *)
          echo "Unrecognized option --${OPTARG}"
          exit 1
          ;;
      esac;;
    *)
      echo "Unrecognized option -$OPT"
      exit 1
      ;;
  esac
done

# Check if there is already a cytools container
containers=$(docker ps -a -q --filter="name=cytools-uid-${userid}")
if [[ "$containers" == "" ]]
then
  exists=false
else
  exists=true
fi

if $exists
then
  echo "A CYTools container already exists!"
  read -p "Do you want to remove it and start a new one? (y/[n]) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]
  then
    exit
  fi
  echo "Stopping and removing old CYTools container..."
  tmp=$(docker stop cytools-uid-${userid})
  # Check if we have to remove the stopped container
  containers=$(docker ps -a -q --filter="name=cytools-uid-${userid}")
  if [[ "$containers" == "" ]]
  then
    exists=false
  else
    exists=true
  fi
  if $exists
  then
    tmp=$(docker rm cytools-uid-${userid})
  fi
fi

cat << EOF

   █████████  █████ █████ ███████████                   ████
  ███░░░░░███░░███ ░░███ ░█░░░███░░░█                  ░░███
 ███     ░░░  ░░███ ███  ░   ░███  ░   ██████   ██████  ░███   █████
░███           ░░█████       ░███     ███░░███ ███░░███ ░███  ███░░
░███            ░░███        ░███    ░███ ░███░███ ░███ ░███ ░░█████
░░███     ███    ░███        ░███    ░███ ░███░███ ░███ ░███  ░░░░███
 ░░█████████     █████       █████   ░░██████ ░░██████  █████ ██████
  ░░░░░░░░░     ░░░░░       ░░░░░     ░░░░░░   ░░░░░░  ░░░░░ ░░░░░░

                Developed by Liam McAllister's Group
                  https://cy.tools | Version 1.4.6

EOF

# Initialize docker container
echo "Initializing CYTools container..."
if $runbash
then
  contid=$(sudo docker run --rm -d -it --name cytools-uid-${userid} -p $port:$port -v $mountdir:/home/cytools/mounted_volume cytools:uid-${userid} bash || echo "failed")
  if [[ "$contid" == "failed" ]]
  then
    echo "The Docker container failed to start."
    echo "Please make sure the CYTools Docker image has been built and that the Docker daemon is running."
    echo "If a custom mount directory was specified please make sure you give its absolute path."
    sleep 10
    exit
  fi
  echo "To exit CYTools press Ctrl+D or use the command 'exit'"
  echo
else
  contid=$(sudo docker run --rm -d -it --name cytools-uid-${userid} -p $port:$port -v $mountdir:/home/cytools/mounted_volume cytools:uid-${userid} || echo "failed")
  if [[ "$contid" == "failed" ]]
  then
    echo "The Docker container failed to start."
    echo "Please make sure the CYTools Docker image has been built and that the Docker daemon is running."
    echo "If a custom mount directory was specified please make sure you give its absolute path."
    sleep 10
    exit
  fi
  # Wait for up to 10 seconds for Jupyter Lab to initialize
  initialized=false
  for n in {1..20}
  do
    sleep .5
    logs=$(docker logs cytools-uid-${userid})
    # Check if logs contain hyperlink
    for l in $logs
    do
      if [[ "$l" == *"127.0.0.1"* ]]
      then
        initialized=true
        link=$l
        break 2
      fi
    done
  done

  if ! $initialized
  then
    echo "Something went wrong. Please make sure the CYTools Docker image has been built."
    sleep 10
    exit
  fi

  # We open the link in a new browser tab
  open $link
  echo "CYTools is now running. If a new tab in your browser was not opened, please copy and paste the following link into your web browser of choice."
  echo "$link"

  echo "To exit CYTools press Ctrl+C twice or close your terminal."
  echo
fi

# We attach the cytools container so that we can see the output and close it when we want to
docker attach cytools-uid-${userid}
