name: Deploy

on:
  workflow_dispatch:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build SDist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: ci-sdist
          path: dist/*.tar.gz

  make-wheel:
    name: Make Wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build Wheel
        run: pipx run build --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: ci-wheel
          path: dist/*.whl

  deploy-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [make-sdist, make-wheel]
    environment:
      name: pypi
      url: https://pypi.org/p/cytools
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v5
        with:
          pattern: ci-*
          path: dist
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
