name: Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build image
        run: echo "\n" | make build-with-root-user # echo because it expects an input
      - name: Push
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          docker tag cytools:root liammcallistergroup/cytools:singularity
          docker push liammcallistergroup/cytools:singularity
